version: "3"

services:
  freshrss-db:
    image: postgres:12-alpine
    container_name: freshrss-db
    hostname: freshrss-db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - freshrss-internal

  freshrss:
    image: freshrss/freshrss:1.19.2
    container_name: freshrss
    hostname: freshrss-app
    restart: unless-stopped
    # ports:
    #   - "${EXPOSED_PORT:-8080}:80"
    depends_on:
      - freshrss-db
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      CRON_MIN: '*/20'
      TZ: Europe/Paris
    networks:
      - freshrss-internal
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`rss.${DOMAIN}`)
      - traefik.http.routers.freshrss.tls.certresolver=lets-encrypt

volumes:
  db:
  data:
  extensions:

networks:
  freshrss-internal:
    external: false
  proxy:
    external: true
